name: Run Number Search Script

on:
  push:
    branches: [ find_indexes ]  # Replace with your actual branch name
  pull_request:
    branches: [ main ]

jobs:
  execute-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your preferred Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy  # Only if you're using numpy in your script
        
    - name: Run number search script
      run: python find_indexes_for_number.py
